name: build docker image

on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup qemu
        uses: docker/setup-qemu-action@v1
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: login to ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          tags: 265389612123.dkr.ecr.eu-central-1.amazonaws.com/frontend:${{ github.sha }}
          push: true
          build-args: |
            NEXT_PUBLIC_TESTNET_GRAPHQL_URL=https://api.whitewhale.money/graphql
      - uses: actions/checkout@v2
        with:
          repository: 'White-Whale-Defi-Platform/tf-infra-dev-apps'
          token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
          path: 'tf-infra-dev-apps'
      - name: commit new version
        working-directory: './tf-infra-dev-apps'
        run: 'sed -i "s/frontend_image_tag = .*/frontend_image_tag = \"${{ github.sha }}\"/g" frontend.auto.tfvars'
      - uses: EndBug/add-and-commit@v5.2.0
        with:
          cwd: 'tf-infra-dev-apps'
          branch: main
          author_name: Whitewhale Service Account
          author_email: aws@whitewhale.finance
          message: 'Bump frontend to ${{ github.sha }}'
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_PAT }}
